# Generated by Django 2.2.12 on 2020-08-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='idade',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
